export const bankLoans = [
  {
    id: 1,
    name: "Panjab National Bank (PNB)",
    shortName: "PNB",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏦",
    color: "from-blue-600 to-blue-400",
    description: "Government Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "50 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Competitive interest rates",
      "Flexible tenure options",
      "No prepayment penalty",
      "Online loan application",
      "Fast disbursement",
    ],
    eligibility: [
      "Age: 21-65 years",
      "Annual income: ₹3 Lakhs minimum",
      "Credit score: 700+",
      "Stable employment history",
    ],
  },
  {
    id: 2,
    name: "HDFC Bank",
    shortName: "HDFC",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏦",
    color: "from-red-600 to-red-400",
    description: "Private Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "1 Crore",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Premium customer benefits",
      "Attractive cashback offers",
      "Insurance coverage included",
      "Quick loan approval",
      "Expert financial counseling",
    ],
    eligibility: [
      "Age: 23-65 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 700+",
      "Existing customer preferred",
    ],
  },
  {
    id: 3,
    name: "LIC Housing Finance",
    shortName: "LIC",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏢",
    color: "from-orange-600 to-orange-400",
    description: "Housing Finance",
    processingFee: "0.5% - 1.5%",
    maxLoanAmount: "50 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "300 months",
    features: [
      "Specialized housing finance",
      "Flexible payment options",
      "Personal accident insurance",
      "LIC policy benefits",
      "Extended tenure options",
    ],
    eligibility: [
      "Age: 21-70 years",
      "Annual income: ₹2 Lakhs minimum",
      "Credit score: 650+",
      "Self-employed/salaried eligible",
    ],
  },
  {
    id: 4,
    name: "IDBI Bank",
    shortName: "IDBI",
    minRate: 6.7,
    maxRate: 7.5,
    logo: "🏦",
    color: "from-green-600 to-green-400",
    description: "Government Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "40 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Best rates for salaried class",
      "Simple documentation",
      "No hidden charges",
      "Quick processing (3 days)",
      "Lifetime support",
    ],
    eligibility: [
      "Age: 21-60 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 700+",
      "Salaried/self-employed",
    ],
  },
];

export const loanTenures = [
  { label: "5 years", value: 60 },
  { label: "10 years", value: 120 },
  { label: "15 years", value: 180 },
  { label: "20 years", value: 240 },
];
